# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OnAMeet < Formula
  desc "CLI tool to detect camera on/off state and trigger commands"
  homepage "https://github.com/sergiocarracedo/on-a-meet"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sergiocarracedo/on-a-meet/releases/download/v1.3.0/on-a-meet_1.3.0_darwin_amd64.tar.gz"
      sha256 "79c701bfcb987f8685ede6be0d201f81b5aa1a87ca2fc0bed0e4db9d1a141ed0"

      define_method(:install) do
        bin.install "on-a-meet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sergiocarracedo/on-a-meet/releases/download/v1.3.0/on-a-meet_1.3.0_darwin_arm64.tar.gz"
      sha256 "126e8c0761b15165faf6b54ded532365633ae4cfe6b49eec785e2ce4d21d463b"

      define_method(:install) do
        bin.install "on-a-meet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiocarracedo/on-a-meet/releases/download/v1.3.0/on-a-meet_1.3.0_linux_amd64.tar.gz"
      sha256 "b0530286a428faa52d13b59579fd612a2b7bc81844572c84e83b81176dc6141b"
      define_method(:install) do
        bin.install "on-a-meet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiocarracedo/on-a-meet/releases/download/v1.3.0/on-a-meet_1.3.0_linux_arm64.tar.gz"
      sha256 "a72c02bff5a941304d134222aa5422c16d34b73d05d9da50b5315a62ec3b14d2"
      define_method(:install) do
        bin.install "on-a-meet"
      end
    end
  end
end
