# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OnAMeet < Formula
  desc "CLI tool to detect camera on/off state and trigger commands"
  homepage "https://github.com/sergiocarracedo/on-a-meet"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sergiocarracedo/on-a-meet/releases/download/v1.2.2/on-a-meet_1.2.2_darwin_amd64.tar.gz"
      sha256 "dd7ec874f49374145f434ecce8e1bf18b151b2324083cfc795187076b206d392"

      define_method(:install) do
        bin.install "on-a-meet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sergiocarracedo/on-a-meet/releases/download/v1.2.2/on-a-meet_1.2.2_darwin_arm64.tar.gz"
      sha256 "210df3ba24473f3ce5e3b39c4ed503f128bd019d63a4a238641e53168c2ea619"

      define_method(:install) do
        bin.install "on-a-meet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiocarracedo/on-a-meet/releases/download/v1.2.2/on-a-meet_1.2.2_linux_amd64.tar.gz"
      sha256 "8f4604f615cbbb3e5eb2e70e4291451279127177abfbf1f946b26921b55f26fa"
      define_method(:install) do
        bin.install "on-a-meet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiocarracedo/on-a-meet/releases/download/v1.2.2/on-a-meet_1.2.2_linux_arm64.tar.gz"
      sha256 "08862ea11e9c71a50356096f592ac5dc4376d974354aa146cbf5b5e0d89b5f09"
      define_method(:install) do
        bin.install "on-a-meet"
      end
    end
  end
end
