# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillOrganizer < Formula
  desc "Organize structured skill trees into flat tool-readable targets"
  homepage "https://github.com/sergiocarracedo/skill-organizer"
  version "1.3.0"
  license "UNLICENSED"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sergiocarracedo/skill-organizer/releases/download/v1.3.0/skill-organizer_1.3.0_Darwin_x86_64.tar.gz"
      sha256 "d6a51868eeef4c181fddeb8aa74b4dbce27005ac0c114f7a0fa8ab217918e74c"

      define_method(:install) do
        bin.install "skill-organizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sergiocarracedo/skill-organizer/releases/download/v1.3.0/skill-organizer_1.3.0_Darwin_arm64.tar.gz"
      sha256 "94c591780bac3b8e1ff30917af8b44be5567d9e52e0a2381f6aad6b4bf200e49"

      define_method(:install) do
        bin.install "skill-organizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiocarracedo/skill-organizer/releases/download/v1.3.0/skill-organizer_1.3.0_Linux_x86_64.tar.gz"
      sha256 "e5893afab5d785af6a27438dd2516d2ef6a3fc17c5b4a824aeda50ba73d92eaf"
      define_method(:install) do
        bin.install "skill-organizer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sergiocarracedo/skill-organizer/releases/download/v1.3.0/skill-organizer_1.3.0_Linux_arm.tar.gz"
      sha256 "1bfb0d9720a2eb6cf20d92d793259e705fe76dd8a72036bbfb9522fc3ce174ae"
      define_method(:install) do
        bin.install "skill-organizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiocarracedo/skill-organizer/releases/download/v1.3.0/skill-organizer_1.3.0_Linux_arm64.tar.gz"
      sha256 "9af27d248bac4efb16d8c731f9bf87279ed292e2f2dd522c709f8a4320cdb25a"
      define_method(:install) do
        bin.install "skill-organizer"
      end
    end
  end

  test do
    system "#{bin}/skill-organizer", "--version"
  end
end
